
package frc.robot.autos;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LBumpStartBumpReturn = new ChoreoTraj(
	    "LBumpStartBumpReturn",
	    OptionalInt.empty(),
	    5.08267,
	    new Pose2d(3.571, 2.57, Rotation2d.fromRadians(0)),
	    new Pose2d(2.817, 2.565, Rotation2d.fromRadians(-2.441))
	);
	public static final ChoreoTraj LBumpSwipeBumpReturn = new ChoreoTraj(
	    "LBumpSwipeBumpReturn",
	    OptionalInt.empty(),
	    5.52876,
	    new Pose2d(2.872, 2.495, Rotation2d.fromRadians(-2.451)),
	    new Pose2d(2.86, 2.478, Rotation2d.fromRadians(-2.421))
	);
	public static final ChoreoTraj LTrenchStartBumpReturn = new ChoreoTraj(
	    "LTrenchStartBumpReturn",
	    OptionalInt.empty(),
	    4.43682,
	    new Pose2d(4.416, 7.48, Rotation2d.fromRadians(0.005)),
	    new Pose2d(2.872, 5.535, Rotation2d.fromRadians(2.402))
	);
	public static final ChoreoTraj LTrenchStartTrenchReturn = new ChoreoTraj(
	    "LTrenchStartTrenchReturn",
	    OptionalInt.empty(),
	    4.9943,
	    new Pose2d(4.416, 7.48, Rotation2d.fromRadians(0.006)),
	    new Pose2d(3.019, 7.213, Rotation2d.fromRadians(3.141))
	);
	public static final ChoreoTraj LTrenchSwipeBumpReturn = new ChoreoTraj(
	    "LTrenchSwipeBumpReturn",
	    OptionalInt.empty(),
	    5.74263,
	    new Pose2d(2.887, 5.604, Rotation2d.fromRadians(2.165)),
	    new Pose2d(2.872, 5.535, Rotation2d.fromRadians(2.356))
	);
	public static final ChoreoTraj LTrenchSwipeTrenchReturn = new ChoreoTraj(
	    "LTrenchSwipeTrenchReturn",
	    OptionalInt.empty(),
	    5.16114,
	    new Pose2d(3.027, 7.212, Rotation2d.fromRadians(0.006)),
	    new Pose2d(3.019, 7.213, Rotation2d.fromRadians(3.141))
	);
	public static final ChoreoTraj RBumpStartBumpReturn = new ChoreoTraj(
	    "RBumpStartBumpReturn",
	    OptionalInt.empty(),
	    5.00785,
	    new Pose2d(3.571, 5.523, Rotation2d.fromRadians(0)),
	    new Pose2d(2.774, 5.477, Rotation2d.fromRadians(2.373))
	);
	public static final ChoreoTraj RBumpSwipeBumpReturn = new ChoreoTraj(
	    "RBumpSwipeBumpReturn",
	    OptionalInt.empty(),
	    5.26381,
	    new Pose2d(2.857, 5.372, Rotation2d.fromRadians(2.437)),
	    new Pose2d(2.857, 5.383, Rotation2d.fromRadians(2.421))
	);
	public static final ChoreoTraj RTrenchStartBumpReturn = new ChoreoTraj(
	    "RTrenchStartBumpReturn",
	    OptionalInt.empty(),
	    4.43581,
	    new Pose2d(4.416, 0.59, Rotation2d.fromRadians(0.005)),
	    new Pose2d(2.852, 2.456, Rotation2d.fromRadians(-2.423))
	);
	public static final ChoreoTraj RTrenchStartTrenchReturn = new ChoreoTraj(
	    "RTrenchStartTrenchReturn",
	    OptionalInt.empty(),
	    5.13955,
	    new Pose2d(4.416, 0.59, Rotation2d.fromRadians(0.006)),
	    new Pose2d(3.019, 0.86, Rotation2d.fromRadians(3.141))
	);
	public static final ChoreoTraj RTrenchSwipeBumpReturn = new ChoreoTraj(
	    "RTrenchSwipeBumpReturn",
	    OptionalInt.empty(),
	    6.00259,
	    new Pose2d(2.887, 2.47, Rotation2d.fromRadians(-2.403)),
	    new Pose2d(2.852, 2.436, Rotation2d.fromRadians(-2.447))
	);
	public static final ChoreoTraj RTrenchSwipeTrenchReturn = new ChoreoTraj(
	    "RTrenchSwipeTrenchReturn",
	    OptionalInt.empty(),
	    5.18747,
	    new Pose2d(3.027, 0.86, Rotation2d.fromRadians(0.006)),
	    new Pose2d(3.019, 0.86, Rotation2d.fromRadians(3.141))
	);
	public static final ChoreoTraj SlopAutoClimb = new ChoreoTraj(
	    "SlopAutoClimb",
	    OptionalInt.empty(),
	    0.94937,
	    new Pose2d(2.436, 5.9, Rotation2d.fromRadians(2.297)),
	    new Pose2d(1.219, 4.754, Rotation2d.fromRadians(3.118))
	);
	public static final ChoreoTraj SlopAutoStart = new ChoreoTraj(
	    "SlopAutoStart",
	    OptionalInt.empty(),
	    2.2535,
	    new Pose2d(3.558, 4.062, Rotation2d.fromRadians(3.118)),
	    new Pose2d(2.436, 5.948, Rotation2d.fromRadians(2.388))
	);
	public static final ChoreoTraj SynergyFarBumpP2 = new ChoreoTraj(
	    "SynergyFarBumpP2",
	    OptionalInt.empty(),
	    1.97211,
	    new Pose2d(7.823, 7.462, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(6.062, 2.517, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj SynergyFarBumpP3 = new ChoreoTraj(
	    "SynergyFarBumpP3",
	    OptionalInt.empty(),
	    2.5323,
	    new Pose2d(6.062, 2.517, Rotation2d.fromRadians(-3.142)),
	    new Pose2d(1.532, 5.406, Rotation2d.fromRadians(2.678))
	);
	public static final ChoreoTraj SynergyP1 = new ChoreoTraj(
	    "SynergyP1",
	    OptionalInt.empty(),
	    1.5254,
	    new Pose2d(3.548, 7.404, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(7.823, 7.402, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj SynergyP2 = new ChoreoTraj(
	    "SynergyP2",
	    OptionalInt.empty(),
	    2.66678,
	    new Pose2d(7.823, 7.404, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(6.215, 5.368, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj SynergyP3 = new ChoreoTraj(
	    "SynergyP3",
	    OptionalInt.empty(),
	    1.60916,
	    new Pose2d(6.215, 5.368, Rotation2d.fromRadians(3.142)),
	    new Pose2d(1.532, 5.406, Rotation2d.fromRadians(2.678))
	);
	public static final ChoreoTraj SynergyP4 = new ChoreoTraj(
	    "SynergyP4",
	    OptionalInt.empty(),
	    2.49784,
	    new Pose2d(1.532, 5.406, Rotation2d.fromRadians(2.678)),
	    new Pose2d(0.87, 5.724, Rotation2d.fromRadians(2.678))
	);
	public static final ChoreoTraj TestPath = new ChoreoTraj(
	    "TestPath",
	    OptionalInt.empty(),
	    4.13803,
	    new Pose2d(2.5, 1, Rotation2d.fromRadians(0)),
	    new Pose2d(2.5, 5, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("LBumpStartBumpReturn", LBumpStartBumpReturn),
		Map.entry("LBumpSwipeBumpReturn", LBumpSwipeBumpReturn),
		Map.entry("LTrenchStartBumpReturn", LTrenchStartBumpReturn),
		Map.entry("LTrenchStartTrenchReturn", LTrenchStartTrenchReturn),
		Map.entry("LTrenchSwipeBumpReturn", LTrenchSwipeBumpReturn),
		Map.entry("LTrenchSwipeTrenchReturn", LTrenchSwipeTrenchReturn),
		Map.entry("RBumpStartBumpReturn", RBumpStartBumpReturn),
		Map.entry("RBumpSwipeBumpReturn", RBumpSwipeBumpReturn),
		Map.entry("RTrenchStartBumpReturn", RTrenchStartBumpReturn),
		Map.entry("RTrenchStartTrenchReturn", RTrenchStartTrenchReturn),
		Map.entry("RTrenchSwipeBumpReturn", RTrenchSwipeBumpReturn),
		Map.entry("RTrenchSwipeTrenchReturn", RTrenchSwipeTrenchReturn),
		Map.entry("SlopAutoClimb", SlopAutoClimb),
		Map.entry("SlopAutoStart", SlopAutoStart),
		Map.entry("SynergyFarBumpP2", SynergyFarBumpP2),
		Map.entry("SynergyFarBumpP3", SynergyFarBumpP3),
		Map.entry("SynergyP1", SynergyP1),
		Map.entry("SynergyP2", SynergyP2),
		Map.entry("SynergyP3", SynergyP3),
		Map.entry("SynergyP4", SynergyP4),
		Map.entry("TestPath", TestPath)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
