
package frc.robot.autos;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LeftStartNeutralOutpost = new ChoreoTraj(
	    "LeftStartNeutralOutpost",
	    OptionalInt.empty(),
	    8.13676,
	    new Pose2d(3.467, 5.603, Rotation2d.fromRadians(-0.928)),
	    new Pose2d(0.293, 0.733, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj OutpostClimb = new ChoreoTraj(
	    "OutpostClimb",
	    OptionalInt.empty(),
	    2.2752,
	    new Pose2d(0.384, 0.671, Rotation2d.fromRadians(0)),
	    new Pose2d(0.995, 2.742, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostClimbRight = new ChoreoTraj(
	    "OutpostClimbRight",
	    OptionalInt.empty(),
	    1.43759,
	    new Pose2d(0.506, 6.005, Rotation2d.fromRadians(-3.128)),
	    new Pose2d(1.001, 4.717, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RightStartNeutralDepot = new ChoreoTraj(
	    "RightStartNeutralDepot",
	    OptionalInt.empty(),
	    7.14248,
	    new Pose2d(3.467, 2.649, Rotation2d.fromRadians(0.755)),
	    new Pose2d(0.416, 5.935, Rotation2d.fromRadians(2.124))
	);
	public static final ChoreoTraj CycleNeutralFirst = new ChoreoTraj(
	    "CycleNeutralFirst",
	    OptionalInt.empty(),
	    4.28324,
	    new Pose2d(3.476, 2.456, Rotation2d.fromRadians(0.935)),
	    new Pose2d(3.495, 2.436, Rotation2d.fromRadians(-2.247))
	);
	public static final ChoreoTraj CycleNeutralSecond = new ChoreoTraj(
	    "CycleNeutralSecond",
	    OptionalInt.empty(),
	    3.45432,
	    new Pose2d(3.456, 2.495, Rotation2d.fromRadians(-2.218)),
	    new Pose2d(3.456, 2.495, Rotation2d.fromRadians(-2.242))
	);
	public static final ChoreoTraj CycleNeutralThird = new ChoreoTraj(
	    "CycleNeutralThird",
	    OptionalInt.empty(),
	    3.66144,
	    new Pose2d(3.495, 2.534, Rotation2d.fromRadians(-2.293)),
	    new Pose2d(3.476, 2.534, Rotation2d.fromRadians(-2.272))
	);
	public static final ChoreoTraj OutpostClimbNeutral = new ChoreoTraj(
	    "OutpostClimbNeutral",
	    OptionalInt.empty(),
	    2.51213,
	    new Pose2d(3.437, 2.475, Rotation2d.fromRadians(-2.195)),
	    new Pose2d(1.059, 2.787, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("LeftStartNeutralOutpost", LeftStartNeutralOutpost),
		Map.entry("OutpostClimb", OutpostClimb),
		Map.entry("OutpostClimbRight", OutpostClimbRight),
		Map.entry("RightStartNeutralDepot", RightStartNeutralDepot),
		Map.entry("CycleNeutralFirst", CycleNeutralFirst),
		Map.entry("CycleNeutralSecond", CycleNeutralSecond),
		Map.entry("CycleNeutralThird", CycleNeutralThird),
		Map.entry("OutpostClimbNeutral", OutpostClimbNeutral)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
