
package frc.robot.autos;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CenterDepot = new ChoreoTraj(
	    "CenterDepot",
	    OptionalInt.empty(),
	    4.42261,
	    new Pose2d(3.723, 4.018, Rotation2d.fromRadians(-3.136)),
	    new Pose2d(2.852, 5.945, Rotation2d.fromRadians(-3.12))
	);
	public static final ChoreoTraj CitrusLeftSide = new ChoreoTraj(
	    "CitrusLeftSide",
	    OptionalInt.empty(),
	    4.27108,
	    new Pose2d(5.62, 5.574, Rotation2d.fromRadians(-0.018)),
	    new Pose2d(2.872, 5.535, Rotation2d.fromRadians(2.503))
	);
	public static final ChoreoTraj CitrusLeftSideSecondPass = new ChoreoTraj(
	    "CitrusLeftSideSecondPass",
	    OptionalInt.empty(),
	    5.58474,
	    new Pose2d(2.93, 5.516, Rotation2d.fromRadians(-3.123)),
	    new Pose2d(2.872, 5.535, Rotation2d.fromRadians(2.494))
	);
	public static final ChoreoTraj CitrusRightSide = new ChoreoTraj(
	    "CitrusRightSide",
	    OptionalInt.empty(),
	    4.80701,
	    new Pose2d(3.632, 2.631, Rotation2d.fromRadians(-0.018)),
	    new Pose2d(2.755, 2.534, Rotation2d.fromRadians(3.129))
	);
	public static final ChoreoTraj CitrusRightSideSecondCycle = new ChoreoTraj(
	    "CitrusRightSideSecondCycle",
	    OptionalInt.empty(),
	    5.64268,
	    new Pose2d(3.632, 2.631, Rotation2d.fromRadians(-0.018)),
	    new Pose2d(2.755, 2.534, Rotation2d.fromRadians(3.129))
	);
	public static final ChoreoTraj CycleNeutralFirst = new ChoreoTraj(
	    "CycleNeutralFirst",
	    OptionalInt.empty(),
	    6.8766,
	    new Pose2d(3.632, 2.475, Rotation2d.fromRadians(-0.017)),
	    new Pose2d(2.987, 2.475, Rotation2d.fromRadians(-0.01))
	);
	public static final ChoreoTraj CycleNeutralFirstLeft = new ChoreoTraj(
	    "CycleNeutralFirstLeft",
	    OptionalInt.empty(),
	    6.72514,
	    new Pose2d(3.671, 5.555, Rotation2d.fromRadians(0.032)),
	    new Pose2d(3.065, 5.544, Rotation2d.fromRadians(0.01))
	);
	public static final ChoreoTraj CycleNeutralSecond = new ChoreoTraj(
	    "CycleNeutralSecond",
	    OptionalInt.empty(),
	    7.62648,
	    new Pose2d(2.929, 2.456, Rotation2d.fromRadians(-2.356)),
	    new Pose2d(3.047, 2.475, Rotation2d.fromRadians(0.017))
	);
	public static final ChoreoTraj CycleNeutralSecondLeft = new ChoreoTraj(
	    "CycleNeutralSecondLeft",
	    OptionalInt.empty(),
	    7.62369,
	    new Pose2d(2.91, 5.563, Rotation2d.fromRadians(2.378)),
	    new Pose2d(2.93, 5.769, Rotation2d.fromRadians(-0.003))
	);
	public static final ChoreoTraj CycleNeutralThird = new ChoreoTraj(
	    "CycleNeutralThird",
	    OptionalInt.empty(),
	    3.67202,
	    new Pose2d(3.495, 2.534, Rotation2d.fromRadians(-2.313)),
	    new Pose2d(3.476, 2.534, Rotation2d.fromRadians(-2.272))
	);
	public static final ChoreoTraj HuskyLeftSide = new ChoreoTraj(
	    "HuskyLeftSide",
	    OptionalInt.empty(),
	    13.40315,
	    new Pose2d(3.632, 5.477, Rotation2d.fromRadians(-0.018)),
	    new Pose2d(2.872, 5.535, Rotation2d.fromRadians(3.129))
	);
	public static final ChoreoTraj LeftBumpDepot = new ChoreoTraj(
	    "LeftBumpDepot",
	    OptionalInt.empty(),
	    7.05771,
	    new Pose2d(3.671, 5.555, Rotation2d.fromRadians(-3.136)),
	    new Pose2d(2.852, 5.945, Rotation2d.fromRadians(-3.12))
	);
	public static final ChoreoTraj LeftShootToMiddle = new ChoreoTraj(
	    "LeftShootToMiddle",
	    OptionalInt.empty(),
	    7.53751,
	    new Pose2d(2.657, 5.633, Rotation2d.fromRadians(-3.13)),
	    new Pose2d(7.783, 2.125, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj LeftStartNeutralOutpost = new ChoreoTraj(
	    "LeftStartNeutralOutpost",
	    OptionalInt.empty(),
	    8.13676,
	    new Pose2d(3.467, 5.603, Rotation2d.fromRadians(-0.928)),
	    new Pose2d(0.293, 0.733, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj LeftTrenchDepot = new ChoreoTraj(
	    "LeftTrenchDepot",
	    OptionalInt.empty(),
	    7.29798,
	    new Pose2d(3.69, 7.504, Rotation2d.fromRadians(-3.136)),
	    new Pose2d(2.852, 5.945, Rotation2d.fromRadians(-3.12))
	);
	public static final ChoreoTraj OutpostClimb = new ChoreoTraj(
	    "OutpostClimb",
	    OptionalInt.empty(),
	    3.67916,
	    new Pose2d(1.313, 0.702, Rotation2d.fromRadians(3.122)),
	    new Pose2d(0.962, 2.475, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostClimbNeutral = new ChoreoTraj(
	    "OutpostClimbNeutral",
	    OptionalInt.empty(),
	    2.51213,
	    new Pose2d(3.437, 2.475, Rotation2d.fromRadians(-2.195)),
	    new Pose2d(1.059, 2.787, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostClimbNeutralLeft = new ChoreoTraj(
	    "OutpostClimbNeutralLeft",
	    OptionalInt.empty(),
	    2.6598,
	    new Pose2d(3.474, 5.329, Rotation2d.fromRadians(2.295)),
	    new Pose2d(0.983, 4.809, Rotation2d.fromRadians(3.119))
	);
	public static final ChoreoTraj OutpostClimbRight = new ChoreoTraj(
	    "OutpostClimbRight",
	    OptionalInt.empty(),
	    5.62887,
	    new Pose2d(2.95, 5.828, Rotation2d.fromRadians(-3.116)),
	    new Pose2d(0.872, 4.743, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RightShootToMiddle = new ChoreoTraj(
	    "RightShootToMiddle",
	    OptionalInt.empty(),
	    4.52411,
	    new Pose2d(2.774, 2.495, Rotation2d.fromRadians(-3.13)),
	    new Pose2d(8.426, 2.495, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RightStartNeutralDepot = new ChoreoTraj(
	    "RightStartNeutralDepot",
	    OptionalInt.empty(),
	    9.05935,
	    new Pose2d(3.632, 2.631, Rotation2d.fromRadians(-0.018)),
	    new Pose2d(2.638, 5.633, Rotation2d.fromRadians(3.129))
	);
	public static final ChoreoTraj TestPath = new ChoreoTraj(
	    "TestPath",
	    OptionalInt.empty(),
	    4.1157,
	    new Pose2d(2.5, 1, Rotation2d.fromRadians(0)),
	    new Pose2d(2.5, 5, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj CitrusLeftSideSecondPassNew = new ChoreoTraj(
	    "CitrusLeftSideSecondPassNew",
	    OptionalInt.empty(),
	    6.23498,
	    new Pose2d(2.93, 5.516, Rotation2d.fromRadians(-3.123)),
	    new Pose2d(2.872, 5.535, Rotation2d.fromRadians(2.494))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("CenterDepot", CenterDepot),
		Map.entry("CitrusLeftSide", CitrusLeftSide),
		Map.entry("CitrusLeftSideSecondPass", CitrusLeftSideSecondPass),
		Map.entry("CitrusRightSide", CitrusRightSide),
		Map.entry("CitrusRightSideSecondCycle", CitrusRightSideSecondCycle),
		Map.entry("CycleNeutralFirst", CycleNeutralFirst),
		Map.entry("CycleNeutralFirstLeft", CycleNeutralFirstLeft),
		Map.entry("CycleNeutralSecond", CycleNeutralSecond),
		Map.entry("CycleNeutralSecondLeft", CycleNeutralSecondLeft),
		Map.entry("CycleNeutralThird", CycleNeutralThird),
		Map.entry("HuskyLeftSide", HuskyLeftSide),
		Map.entry("LeftBumpDepot", LeftBumpDepot),
		Map.entry("LeftShootToMiddle", LeftShootToMiddle),
		Map.entry("LeftStartNeutralOutpost", LeftStartNeutralOutpost),
		Map.entry("LeftTrenchDepot", LeftTrenchDepot),
		Map.entry("OutpostClimb", OutpostClimb),
		Map.entry("OutpostClimbNeutral", OutpostClimbNeutral),
		Map.entry("OutpostClimbNeutralLeft", OutpostClimbNeutralLeft),
		Map.entry("OutpostClimbRight", OutpostClimbRight),
		Map.entry("RightShootToMiddle", RightShootToMiddle),
		Map.entry("RightStartNeutralDepot", RightStartNeutralDepot),
		Map.entry("TestPath", TestPath),
		Map.entry("CitrusLeftSideSecondPassNew", CitrusLeftSideSecondPassNew)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
